version: '3'

services:
  jackrabbit:
    build: .
    environment:
      RABBIT_URL: 'amqp://rabbit'
    restart: on-failure
  rabbit:
    image: rabbitmq@sha256:437ea77f0651165726384bab7863578aee792805451badf712e71ebe8b68931b
    ports:
      - "5672:5672"
